version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  upload_service:
    build: ./upload_service
    container_name: upload_service
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./upload_service/uploads:/app/uploads
    depends_on:
      - redis
    restart: always

  retriever_service:
    build: ./retriever_service
    container_name: retriever_service
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - UPLOAD_SERVICE_URL=http://upload_service:5000
      - SIMILARITY_THRESHOLD=0.9
    volumes:
      - ./retriever_service/downloaded_images:/app/downloaded_images
      - ./retriever_service/cctv_inputs:/app/cctv_inputs
    depends_on:
      - upload_service
      - redis
    restart: always